name: science_chatbot  # Add this line (use lowercase_with_underscores)
description: A science chatbot application.  # Optional but recommended
version: 1.0.0+1  # Optional but recommended

environment:
  sdk: '>=3.0.0 <4.0.0'  # Ensure this matches your Dart SDK

dependencies:
  flutter_pdfview: ^1.4.0+1  # For PDF viewing
  # pdfx: ^1.3.3  # Alternative PDF viewer
  http: ^1.3.0  # For downloading PDFs
  path_provider: ^2.1.1  # For file storage
  firebase_auth: ^5.5.3
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  provider: ^6.1.5
  flutter_typeahead: ^5.2.0
  ml_linalg: ^13.12.6
  dart_levenshtein: ^1.0.1
  flutter_onnxruntime: ^1.4.0
  flutter_tts: ^4.2.2
  csv: ^6.0.0
  tflite_flutter: ^0.11.0
  string_similarity: ^2.1.1
  firebase_database: ^11.3.5
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  youtube_player_flutter: ^9.1.1

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
  assets:
    - assets/images/bot.png
    - assets/images/student.png
    - assets/images/googleicon.png
    - assets/images/books.png
    - assets/images/logo.png
    - assets/images/avtar.png
    - assets/images/science.png
    - assets/images/home-btn.png
    - assets/images/resource-btn.png
    - assets/images/chatbot-btn.png
    - assets/images/profile-btn.png
    - assets/images/quiz-btn.png
    - assets/images/science2.png
    - assets/images/nextImage.png
    - assets/images/eye_open.png
    - assets/images/eye_closed.png
    - assets/images/menu-lines.png
    - assets/images/search-btn.png
    - assets/images/logout.png
    - assets/images/home.png
    - assets/images/profile.png
    - assets/sciencebot.onnx
    - assets/vectorizer.joblib
    - assets/questions_list.csv
    - assets/biology_qa_dataset.csv
    - assets/images/Fivekingdom.png
    - assets/images/Bacteria.png
    - assets/images/Chlorella.png
    - assets/images/Entamoeba.png
    - assets/images/Fungi.png
    - assets/images/Organisms_from_Kingdom_Protista.png
    - assets/images/Organisms_from_Kingdom_Monera.png
    - assets/images/Paramoecium.png
    - assets/images/Plasmodium.png
    - assets/images/Saccharomyces.png
    - assets/sciencebot.onnx
    - assets/images/mute.png
    - assets/images/volume-up.png
    - assets/images/sci-chp1.png
    - assets/images/sci-chp2.png
    - assets/Science-chp1.pdf
    - assets/Science-chp2.pdf
    - assets/images/bubble-chat.png
    - assets/images/home1.png
    - assets/images/ideas.png
    - assets/images/resource.png
    - assets/images/user.png
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter_icons:
  android: true
  image_path: "assets/images/app-icon3.jpg"