// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9kqCcXhqRTs6f7wV-fMRp8lifGFTy6q4',
    appId: '1:619984638366:web:ce21fbf6b230ac37b1868f',
    messagingSenderId: '619984638366',
    projectId: 'logindata-b3d32',
    authDomain: 'logindata-b3d32.firebaseapp.com',
    storageBucket: 'logindata-b3d32.firebasestorage.app',
    measurementId: 'G-NNQ6TSFECZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGgGND4WLk_WljyXcKTRaOw30IBWZnl0A',
    appId: '1:619984638366:android:c5312f4d7adcc37bb1868f',
    messagingSenderId: '619984638366',
    projectId: 'logindata-b3d32',
    storageBucket: 'logindata-b3d32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA46LxtQeyJPZuZDKNrVgV_HYocNCGhfHY',
    appId: '1:619984638366:ios:c76d0958e62e6574b1868f',
    messagingSenderId: '619984638366',
    projectId: 'logindata-b3d32',
    storageBucket: 'logindata-b3d32.firebasestorage.app',
    iosBundleId: 'com.example.scienceChatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA46LxtQeyJPZuZDKNrVgV_HYocNCGhfHY',
    appId: '1:619984638366:ios:c76d0958e62e6574b1868f',
    messagingSenderId: '619984638366',
    projectId: 'logindata-b3d32',
    storageBucket: 'logindata-b3d32.firebasestorage.app',
    iosBundleId: 'com.example.scienceChatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9kqCcXhqRTs6f7wV-fMRp8lifGFTy6q4',
    appId: '1:619984638366:web:d508f3acbf900eb6b1868f',
    messagingSenderId: '619984638366',
    projectId: 'logindata-b3d32',
    authDomain: 'logindata-b3d32.firebaseapp.com',
    storageBucket: 'logindata-b3d32.firebasestorage.app',
    measurementId: 'G-3JXN9YMR0S',
  );

}